name: RadioChat
version: 01.00.12
main: me.capit.RadioChat.RadioChat

website: https://github.com/Wehttam664/RadioChat/wiki
description: GameData_RadioChat
author: Wehttam664
preix: RadioChat
    
commands:
  broadcast:
    description: 'Broadcasts a message.'
    usage: broadcast <message>
    permission: radiochat.broadcast
    
permissions:
  radiochat.broadcast:
    description: 'Broadcast a global message.'
